### ISSUE TITLE
Unbound variable

### ISSUE THREAD

**Issue by ch9PcB** [wknapik/vpnfailsafe#3] opened 2016-11-26 16:46 UTC
Below is a portion of the error message when I was trying to connect to a VPN server:

    Fri Nov 25 00:00:00 2016 /etc/openvpn/vpnfailsafe.sh tap0 1502 1578 10.10.20.3 255.255.255.0 init
    /etc/openvpn/vpnfailsafe.sh:38: `local -ar remote_ips=($(getent -s files hosts "${remotes[@]}"|cut -d' ' -f1))' returned 2
    /etc/openvpn/vpnfailsafe.sh: line 51: remote_ips[@]: unbound variable
    /etc/openvpn/vpnfailsafe.sh: line 40: remote_ips[@]: unbound variable
    Fri Nov 25 00:00:00 2016 WARNING: Failed running command (--up/--down): external program exited with error status: 1
    Fri Nov 25 00:00:00 2016 Exiting due to fatal error

Some useful information:

1. Debian 8, 64-bit (updates applied whenever available from Debian)
2. OpenVPN 2.3.13 (openvpn_2.3.13-jessie0_amd64.deb)
3. resolvconf (version 1.76.1)
4. /etc/openvpn/update-resolv-conf
5. /etc/openvpn/vpnfailsafe.sh

**Comment by wknapik** [comment] 2016-11-26 17:46
Hi @ch9PcB. It seems you're using a tap-device-based VPN - that's ethernet encapsulation. vpnfailsafe was written for tun-device-based connections, which encapsulate IP traffic (as mentioned [here](https://github.com/wknapik/vpnfailsafe#what-are-the-requirementsassumptionslimitations-)). I've never used the former, but given access to one, I could see if adapting vpnfailsafe would be feasible. 

There's plenty of info regarding tun vs. tap setups [out there](https://encrypted.google.com/search?q=openvpn+vpn+tun+vs+tap), if you'd like to know more. In the vast majority of cases, a tun setup is preferable. Your VPN provider might already be offering such an option - if that's the case and you can switch, vpnfailsafe will probably work for you. Otherwise, I'm afraid I can't be of much help.

Out of curiosity, if it's not confidential, what VPN provider are you using ?

**Comment by wknapik** [comment] 2016-11-26 18:03
Actually, the first error you got is caused by something else - the incorrect assumption that a domain will always be used to specify remotes. When an IP is used instead, this line fails, but it seems the script manages to do everything it needs to regardless. I'll push a fix for this today.

**Comment by wknapik** [comment] 2016-11-27 03:40
Ok, pushed a change that allows using any mix of domain names and IPs for remotes.

@ch9PcB - this may resolve your problem, please update and retest.

**Comment by ch9PcB** [comment] 2016-11-27 05:29
Hi @wknapik 

Thanks for your prompt reply.

(1) Is it difficult to adapt vpnfailsafe to tap devices?

(2) I have just downloaded the amended vpnfailsafe.sh and below is the error:

    Sat Nov 26 00:00:00 2016 TUN/TAP device tap0 opened
    Sat Nov 26 00:00:00 2016 TUN/TAP TX queue length set to 100
    Sat Nov 26 00:00:00 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
    Sat Nov 26 00:00:00 2016 /sbin/ip link set dev tap0 up mtu 1502
    Sat Nov 26 00:00:00 2016 /sbin/ip addr add dev tap0 10.10.20.3/24 broadcast 10.10.20.255
    Sat Nov 26 00:00:00 2016 /etc/openvpn/vpnfailsafe.sh tap0 1502 1578 10.10.20.3 255.255.255.0 init
    /etc/openvpn/vpnfailsafe.sh: line 31: cnf_remote_domains[@]: unbound variable
    /etc/openvpn/vpnfailsafe.sh: line 45: resolved_ips[@]: unbound variable
    Sat Nov 26 00:00:00 2016 WARNING: Failed running command (--up/--down): external program exited with error status: 1
    Sat Nov 26 00:00:00 2016 Exiting due to fatal error

(3) On the first page of your introduction to vpnfailsafe, there is a typo in the heading "What is vpnailsafe ?". An "f" is missing between "n" and "a".

**Comment by ch9PcB** [comment] 2016-11-27 06:17
Hi @wknapik 

I was wondering if you could write a script similar in functionality to vpnfailsafe for OpenBSD?

**Comment by wknapik** [comment] 2016-11-27 16:07
(1) I have no idea. If you're using a commercial VPN provider, where I could get an account, I could take a look and find out. 

(2) Yeah, this might be where the differences between tun and tap begin. But it might be something else as well. Can you post your config somewhere ? Also, if you could add: `set -x; env` in the second line of vpnfailsafe.sh and post the full output, that could help in figuring this out. But honestly, to properly look into, I'd need access to a tap-based VPN.

(3) Hah, thanks. I don't know how I could've missed it.

(4) As for OpenBSD - I've played with it some years ago, but these days I'm on Arch. Porting to bsd would require rewriting at least the code that uses iproute2 (not a big deal) and iptables (a bigger deal to be sure - I'd have to learn pf), but there would probably be more... I work on open source stuff in my spare time, which is limited. Things that scratch an itch for me do take precedence, so I can't promise anything. At this point that's a "maybe, but don't hold your breath".

Please add two separate github issues as feature requests - "Support for TAP devices" and "Support for OpenBSD".
Right now I'm working on another OpenVPN related project, that will make it very easy to use OpenVPN as an unprivileged user. Once I'm done with it, I'll pick the next thing to do, possibly one of these new features. I like the idea of supporting TAP in vpnfailsafe, so there's a good chance I'll pick this.

Thanks for the report.

**Comment by ch9PcB** [comment] 2016-11-27 18:08
Hello @wknapik 

(1) Yes, the errors that I mentioned in my earlier posts occurred when I was using a commercial VPN provider. Does GitHub offer a secure private messaging service? If it does I can send you a link with which you can download the exact config files and authentication certificates.

(2) Below is a sample of the config file provided by my commercial VPN provider. I have obfuscated the relevant details:

    remote 1.2.3.4 1195 tcp
    auth-user-pass user.txt
    up 'update-resolv-conf'
    down 'update-resolv-conf'
    link-mtu 1578
    dev tap
    server-poll-timeout 20
    client
    nobind
    resolv-retry infinite
    auth-retry nointeract
    persist-key
    persist-tun
    mute-replay-warnings
    comp-lzo
    verb 3
    mute 20
    ns-cert-type server
    route-method exe
    route-delay 2
    script-security 3 system
    reneg-sec 0
    <ca>
    -----BEGIN CERTIFICATE-----
    MIIsjwomcpmwmcbwgvqncoc
    -----END CERTIFICATE-----
    </ca>

(3) It is not just config files with tap device that have problems with vpnfailsafe.sh. *Config files with tun device also encounter the same errors with vpnfailsafe.sh.*

Please surf to [VPN Gate](http://www.vpngate.net/en/) from where you can download free config files of your choice. (A word of caution: Do not use the free service provided by volunteers of VPN Gate for confidential stuff. For all you know, some of the volunteers could be intelligence services belonging to rogue nations.)

The config files that you find at VPN Gate all use tun device. If you use vpnfailsafe.sh with them, you will get the same errors as I did with my commercial VPN provider. How do I know? I tried vpnfailsafe.sh with them a few hours before I read your most recent reply.

(4) As requested I shall put forward two feature requests: "Support for TAP device" and "Support for OpenBSD".

(5) Awesome. I am glad you are actively contributing to OpenVPN projects. Are you aware that OpenVPN developers and users are active on a forum hosted by Sourceforge?

**Comment by wknapik** [comment] 2016-11-28 23:44
(1) I've made my email available on my github profile page. Feel free to encrypt your message using my pgp key (importable from keys.gnupg.net et al).

(2) Nothing obviously problematic here.

(3) Interesting. I will definitely look into it.

(4) Thanks.

(5) I am not a big fan of sourceforge, nor forums in general. I've visited the freenode channel a few times. Still, good to know about it.

I will do some testing with the VPN Gate VPNs and hopefully pin down the problem quickly. I'm going on holidays shortly, but will try to work on this as time permits. Will let you know when there's progress. Cheers.

**Comment by ch9PcB** [comment] 2016-11-29 12:16
Hi @wknapik 

I have just sent you an email. If you have some spare time, please have a look at it.

OpenVPN developers and people who are IT pros like you subscribe to [OpenVPN Mailing Lists](https://sourceforge.net/p/openvpn/mailman/) and that is where they discuss their highly technical stuff.

Regards.

**Comment by wknapik** [comment] 2016-12-01 15:35
Hi @ch9PcB. I was able to connect to your VPN provider, as well as several VPN Gate servers (in several countries, over tcp and udp, on different ports) using vpnfailsafe, with no issues. This seems like some issue on your end. Please add `set -x; env` in the second line of vpnfailsafe.sh and send me the output printed when vpnfailsafe is executed after the connection is established (--up). Also, what bash version are you using ?

**Comment by jkaberg** [comment] 2016-12-01 18:24
@wknapik I just tried you're script using an tun device and I'm running into the same error. Here's the output,

```
Thu Dec  1 19:21:57 2016 /etc/openvpn/vpnfailsafe.sh tun0 1500 1601 193.183.116.48 255.255.255.224 init
+ env
dev_type=tun
X509_1_OU=AzireVPN
common_name=ovpn.azirevpn.net
untrusted_ip=193.180.164.35
ifconfig_local=193.183.116.48
proto_2=udp
proto_1=udp
tls_serial_1=13029366427188636458
ifconfig_ipv6_remote=2a03:8600:1001:1022::1
tls_serial_0=1
tun_mtu=1500
ifconfig_ipv6_netbits=64
X509_1_emailAddress=info@azirevpn.com
ifconfig_netmask=255.255.255.224
tls_id_0=C=SE, ST=Stockholm, L=Stockholm, O=AzireVPN, OU=AzireVPN, CN=ovpn.azirevpn.net, name=AzireVPN, emailAddress=info@azirevpn.com
foreign_option_1=dhcp-option DNS 193.180.164.2
X509_1_L=Stockholm
tls_id_1=C=SE, ST=Stockholm, L=Stockholm, O=AzireVPN, OU=AzireVPN, CN=ovpn.azirevpn.net, name=AzireVPN, emailAddress=info@azirevpn.com
ifconfig_ipv6_local=2a03:8600:1001:1022::100e
X509_1_O=AzireVPN
script_type=up
verb=3
local_port_1=0
local_port_2=0
config=/etc/openvpn/vpn.conf
route_ipv6_network_1=2000::/3
X509_0_CN=ovpn.azirevpn.net
trusted_port=1194
dev=tun0
X509_1_C=SE
X509_1_ST=Stockholm
remote_port_1=1194
tls_serial_hex_1=b4:d1:9b:bb:a4:fa:ab:2a
PWD=/etc/openvpn
tls_serial_hex_0=01
remote_port_2=443
daemon=1
route_net_gateway=192.168.1.1
X509_1_name=AzireVPN
ifconfig_broadcast=193.183.116.63
untrusted_port=1194
SHLVL=1
route_vpn_gateway=193.183.116.33
script_context=init
daemon_start_time=1480616514
trusted_ip=193.180.164.35
X509_0_ST=Stockholm
daemon_pid=3602
route_ipv6_gateway_1=2a03:8600:1001:1022::1
X509_1_CN=ovpn.azirevpn.net
X509_0_OU=AzireVPN
X509_0_emailAddress=info@azirevpn.com
X509_0_name=AzireVPN
daemon_log_redirect=1
CLIENT_CERT=0
tls_digest_1=17:af:ca:25:31:d7:fc:88:d9:b8:b8:d2:38:5e:5c:39:ad:1d:b0:7d
X509_0_C=SE
tls_digest_0=20:22:9a:a8:a9:f6:0f:f4:3d:c6:41:a9:09:90:95:73:a2:d7:9b:74
X509_0_L=Stockholm
remote_2=se.ovpn.azirevpn.net
link_mtu=1601
remote_1=se.ovpn.azirevpn.net
X509_0_O=AzireVPN
_=/usr/bin/env
+ set -eEuo pipefail
+ readonly dev
+ readonly foreign_option_1
+ readonly ifconfig_local
+ readonly ifconfig_netmask
+ readonly ifconfig_remote
+ readonly proto_1 proto_2
+ readonly remote_1 remote_2 remote_port_1 remote_port_2
+ readonly remote_port_1 remote_port_2
+ readonly route_net_gateway
+ readonly route_vpn_gateway
+ readonly script_type
+ readonly trusted_ip
+ readonly trusted_port
+ readonly untrusted_ip
+ readonly untrusted_port
++ basename /etc/openvpn/vpnfailsafe.sh
+ readonly prog=vpnfailsafe.sh
+ prog=vpnfailsafe.sh
+ readonly private_nets=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
+ private_nets=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
+ remotes=($(env|grep -oP 'remote_[0-9]+=.*'|sort -n|cut -d= -f2))
++ env
++ grep -oP 'remote_[0-9]+=.*'
++ sort -n
++ cut -d= -f2
+ readonly -a remotes
+ cnf_remote_domains=(${remotes[@]%%*[0-9]})
+ readonly -a cnf_remote_domains
+ cnf_remote_ips=(${remotes[@]##*[!0-9.]*})
+ readonly -a cnf_remote_ips
+ readonly cur_remote_ip=193.180.164.35
+ cur_remote_ip=193.180.164.35
+ readonly cur_port=1194
+ cur_port=1194
+ trap cleanup INT TERM
+ trap 'err_msg "$LINENO" "$?"' ERR
+ main
+ case "${script_type:-down}" in
+ for f in hosts routes resolv firewall
+ update_hosts up
++ getent -s dns hosts se.ovpn.azirevpn.net se.ovpn.azirevpn.net
++ grep -v :
+ remote_entries='193.180.164.35  se.ovpn.azirevpn.net
193.180.164.47  se.ovpn.azirevpn.net
193.180.164.44  se.ovpn.azirevpn.net
193.180.164.37  se.ovpn.azirevpn.net
193.180.164.34  se.ovpn.azirevpn.net
193.180.164.48  se.ovpn.azirevpn.net
193.180.164.43  se.ovpn.azirevpn.net
193.180.164.49  se.ovpn.azirevpn.net
193.180.164.46  se.ovpn.azirevpn.net
193.180.164.45  se.ovpn.azirevpn.net
193.180.164.56  se.ovpn.azirevpn.net
193.180.164.36  se.ovpn.azirevpn.net
193.180.164.39  se.ovpn.azirevpn.net
193.180.164.52  se.ovpn.azirevpn.net
193.180.164.55  se.ovpn.azirevpn.net
193.180.164.53  se.ovpn.azirevpn.net
193.180.164.50  se.ovpn.azirevpn.net
193.180.164.51  se.ovpn.azirevpn.net
193.180.164.42  se.ovpn.azirevpn.net
193.180.164.40  se.ovpn.azirevpn.net
193.180.164.38  se.ovpn.azirevpn.net
193.180.164.41  se.ovpn.azirevpn.net
193.180.164.54  se.ovpn.azirevpn.net
193.180.164.57  se.ovpn.azirevpn.net
193.180.164.46  se.ovpn.azirevpn.net
193.180.164.40  se.ovpn.azirevpn.net
193.180.164.57  se.ovpn.azirevpn.net
193.180.164.47  se.ovpn.azirevpn.net
193.180.164.35  se.ovpn.azirevpn.net
193.180.164.50  se.ovpn.azirevpn.net
193.180.164.41  se.ovpn.azirevpn.net
193.180.164.56  se.ovpn.azirevpn.net
193.180.164.52  se.ovpn.azirevpn.net
193.180.164.55  se.ovpn.azirevpn.net
193.180.164.45  se.ovpn.azirevpn.net
193.180.164.36  se.ovpn.azirevpn.net
193.180.164.48  se.ovpn.azirevpn.net
193.180.164.44  se.ovpn.azirevpn.net
193.180.164.38  se.ovpn.azirevpn.net
193.180.164.39  se.ovpn.azirevpn.net
193.180.164.42  se.ovpn.azirevpn.net
193.180.164.34  se.ovpn.azirevpn.net
193.180.164.51  se.ovpn.azirevpn.net
193.180.164.54  se.ovpn.azirevpn.net
193.180.164.37  se.ovpn.azirevpn.net
193.180.164.49  se.ovpn.azirevpn.net
193.180.164.43  se.ovpn.azirevpn.net
193.180.164.53  se.ovpn.azirevpn.net'
+ local -r 'beg=# VPNFAILSAFE BEGIN' 'end=# VPNFAILSAFE END'
+ sed -e '/^# VPNFAILSAFE BEGIN/,/^# VPNFAILSAFE END/d' /etc/hosts
+ echo -e '# VPNFAILSAFE BEGIN\n193.180.164.35  se.ovpn.azirevpn.net
193.180.164.47  se.ovpn.azirevpn.net
193.180.164.44  se.ovpn.azirevpn.net
193.180.164.37  se.ovpn.azirevpn.net
193.180.164.34  se.ovpn.azirevpn.net
193.180.164.48  se.ovpn.azirevpn.net
193.180.164.43  se.ovpn.azirevpn.net
193.180.164.49  se.ovpn.azirevpn.net
193.180.164.46  se.ovpn.azirevpn.net
193.180.164.45  se.ovpn.azirevpn.net
193.180.164.56  se.ovpn.azirevpn.net
193.180.164.36  se.ovpn.azirevpn.net
193.180.164.39  se.ovpn.azirevpn.net
193.180.164.52  se.ovpn.azirevpn.net
193.180.164.55  se.ovpn.azirevpn.net
193.180.164.53  se.ovpn.azirevpn.net
193.180.164.50  se.ovpn.azirevpn.net
193.180.164.51  se.ovpn.azirevpn.net
193.180.164.42  se.ovpn.azirevpn.net
193.180.164.40  se.ovpn.azirevpn.net
193.180.164.38  se.ovpn.azirevpn.net
193.180.164.41  se.ovpn.azirevpn.net
193.180.164.54  se.ovpn.azirevpn.net
193.180.164.57  se.ovpn.azirevpn.net
193.180.164.46  se.ovpn.azirevpn.net
193.180.164.40  se.ovpn.azirevpn.net
193.180.164.57  se.ovpn.azirevpn.net
193.180.164.47  se.ovpn.azirevpn.net
193.180.164.35  se.ovpn.azirevpn.net
193.180.164.50  se.ovpn.azirevpn.net
193.180.164.41  se.ovpn.azirevpn.net
193.180.164.56  se.ovpn.azirevpn.net
193.180.164.52  se.ovpn.azirevpn.net
193.180.164.55  se.ovpn.azirevpn.net
193.180.164.45  se.ovpn.azirevpn.net
193.180.164.36  se.ovpn.azirevpn.net
193.180.164.48  se.ovpn.azirevpn.net
193.180.164.44  se.ovpn.azirevpn.net
193.180.164.38  se.ovpn.azirevpn.net
193.180.164.39  se.ovpn.azirevpn.net
193.180.164.42  se.ovpn.azirevpn.net
193.180.164.34  se.ovpn.azirevpn.net
193.180.164.51  se.ovpn.azirevpn.net
193.180.164.54  se.ovpn.azirevpn.net
193.180.164.37  se.ovpn.azirevpn.net
193.180.164.49  se.ovpn.azirevpn.net
193.180.164.43  se.ovpn.azirevpn.net
193.180.164.53  se.ovpn.azirevpn.net\n# VPNFAILSAFE END'
+ chmod --reference=/etc/hosts /etc/hosts.vpnfailsafe
+ mv /etc/hosts.vpnfailsafe /etc/hosts
+ for f in hosts routes resolv firewall
+ update_routes up
+ resolved_ips=($(getent -s files hosts "${cnf_remote_domains[@]:-!NONE!}"|cut -d' ' -f1 || true))
++ getent -s files hosts se.ovpn.azirevpn.net se.ovpn.azirevpn.net
++ cut '-d ' -f1
+ local -ar resolved_ips
+ remote_ips=("${resolved_ips[@]}" "${cnf_remote_ips[@]}")
/etc/openvpn/vpnfailsafe.sh: line 45: cnf_remote_ips[@]: unbound variable
Thu Dec  1 19:21:57 2016 WARNING: Failed running command (--up/--down): external program exited with error status: 1
Thu Dec  1 19:21:57 2016 Exiting due to fatal error
```

**Comment by wknapik** [comment] 2016-12-01 18:49
Thanks for the report @jkaberg. I'll take a closer look at this tomorrow. I think I see the problem, but can't work on this right now. Will let you know when I have something.

**Comment by wknapik** [comment] 2016-12-02 16:54
Ok, the problem is most likely caused by different behavior of the bash versions we're using.

The handling of "${arr[@]}" for empty arrays changed in 4.4. Will push a fix for this today.

**Comment by wknapik** [comment] 2016-12-02 18:03
Ok, @ch9PcB, @jkaberg - you can update to the latest version and everything should work.

I can't say I like those latest changes, but since major distros still don't use bash 4.4, there's really no other choice. I'll probably drop `set -u` in the future and this will make the workaround added today unnecessary.

Tests with bash 4.3 and AzireVPN/VPN Gate passed for me. Let me know if things are working for you as well.

**Comment by ch9PcB** [comment] 2016-12-04 17:59
Hi @wknapik 

Sorry I missed your question. The bash version that I am using is 4.3

**Comment by ch9PcB** [comment] 2016-12-04 18:09
Hi @wknapik 

Here's my feedback on using the latest version of vpnfailsafe.

It is working in the sense that I am able to connect to a VPN server and once the connection is established, I am able to surf the internet.

After I have manually terminated the VPN connection, I am unable to ping websites. It shows that vpnfailsafe is doing exactly what it has been programmed to do.

However the VPN connection log reported some errors:

    RTNETLINK answers: File exists
    Sun Dec   4 13:00:00 2016 ERROR: Linux route add command failed: external program exited with error status: 2
    Sun Dec   4 13:00:00 2016 /sbin/ip route add 0.0.0.0/1 via 10.10.10.1
    RTNETLINK answers: File exists
    Sun Dec   4 13:00:00 2016 ERROR: Linux route add command failed: external program exited with error status: 2
    Sun Dec   4 13:00:00 2016 /sbin/ip route add 128.0.0.0/1 via 10.10.10.1
    RTNETLINK answers: File exists
    Sun Dec   4 13:00:00 2016 ERROR: Linux route add command failed: external program exited with error status: 2
    Sun Dec   4 13:00:00 2016 Initialization Sequence Completed

I am not proficient in IT and would appreciate it if you could explain:

1. *What* was trying to add a route to *what* program and *why* it failed?
2. *What* is the name of the external program?
3. *What* does "error status: 2" mean?

Thanks.

**Comment by ch9PcB** [comment] 2016-12-04 18:36
Hi @wknapik 

If I use vpnfailsafe.sh, the message *Initialization Sequence Completed* takes about:

(a) 20 seconds longer to appear than when I do not use vpnfailsafe.sh in an ovpn file.
(b) 15 seconds longer to appear than when I use a script containing iptables firewall rules

**Comment by wknapik** [comment] 2016-12-04 22:33
Hi @ch9PcB. The RTNETLINK errors can be safely ignored, as explained [here](https://github.com/wknapik/vpnfailsafe/blob/master/README.md#what-are-the-requirementsassumptionslimitations-).

The reason for the delay is not clear, but I won't be able to investigate that for a few days.

The problem originally reported in this issue is resolved though, so I'll close it. Feel free to open a new issue for the delay.

**Closed as completed by wknapik** 2016-12-04 22:33 UTC
