### ISSUE TITLE
resolvconf: Error: Command not recognized

### ISSUE THREAD

**Issue by userhere** [wknapik/vpnfailsafe#23] opened 2017-12-06 01:17 UTC
resolvconf: Error: Command not recognized
Usage: resolvconf (-d IFACE|-a IFACE|-u|--enable-updates|--disable-updates|--updates-are-enabled)
/etc/openvpn/vpnfailsafe.sh:79: `echo -e "${domains/ /search }\n${ns// /$'\n'nameserver }"|resolvconf -xa "$dev"' returned 99
WARNING: Failed running command (--up/--down): external program exited with error status: 99

Debian stretch 9.2.1
Resolvconf version 1.79

**Comment by wknapik** [comment] 2017-12-07 15:38
As the message says, we're invoking `resolvconf -xa` and your resolvconf version does not support the `-x` switch. 

This was reported [here](https://github.com/wknapik/vpnfailsafe/issues/21), [here](https://github.com/wknapik/vpnfailsafe/issues/13#issuecomment-314678151) and [here](https://github.com/wknapik/vpnfailsafe/issues/20). You need to update to a more recent version of the resolvconf tool.

Since you're on Debian, I suggest you just switch to the openresolv package (replaces the resolvconf package). That should fix the problem.

**Comment by newuserhere** [comment] 2017-12-14 03:26
Does this look good?
What about this lines?
UDP link local: (not bound)
WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Option 'explicit-exit-notify' in [PUSH-OPTIONS]:7 is ignored by previous <connection> blocks
Too few arguments.
Too few arguments.
RTNETLINK answers: File exists
ERROR: Linux route add command failed: external program exited with error status: 2

Log here
WARNING: file '/etc/openvpn/ovpn-tls.key' is group or others accessible
OpenVPN 2.4.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017
library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
TCP/UDP: Preserving recently used remote address: [AF_INET] ipaddress:port
UDP link local: (not bound)
UDP link remote: [AF_INET] ipaddress:port
WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
[ovpn.se] Peer Connection Initiated with [AF_INET] ipaddress:port
Option 'explicit-exit-notify' in [PUSH-OPTIONS]:7 is ignored by previous <connection> blocks
TUN/TAP device tun0 opened
do_ifconfig, tt->did_ifconfig_ipv6_setup=0
/sbin/ip link set dev tun0 up mtu 1500
/sbin/ip addr add dev tun0 ipaddress/** broadcast ipaddress
/etc/openvpn/vpnfailsafe.sh tun0 1500 1553 ipaddress ipaddress init
Too few arguments.
Too few arguments.
RTNETLINK answers: File exists
ERROR: Linux route add command failed: external program exited with error status: 2
RTNETLINK answers: File exists
ERROR: Linux route add command failed: external program exited with error status: 2
RTNETLINK answers: File exists
ERROR: Linux route add command failed: external program exited with error status: 2
Initialization Sequence Completed

**Comment by wknapik** [comment] 2017-12-15 10:40
Hi. This output looks mostly fine.

> WARNING: file '/etc/openvpn/ovpn-tls.key' is group or others accessible

You might want to `chmod 600 /etc/openvpn/ovpn-tls.key`, or something.

> OpenVPN 2.4.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017
> library versions: OpenSSL 1.0.2l 25 May 2017, LZO 2.08
> NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> TCP/UDP: Preserving recently used remote address: [AF_INET] ipaddress:port
> UDP link local: (not bound)
> UDP link remote: [AF_INET] ipaddress:port
> WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> [ovpn.se] Peer Connection Initiated with [AF_INET] ipaddress:port
> Option 'explicit-exit-notify' in [PUSH-OPTIONS]:7 is ignored by previous blocks

Not sure what would disable explicit-exit-notify.
It's nothing to be concerned about, but it's a useful option.

> TUN/TAP device tun0 opened
> do_ifconfig, tt->did_ifconfig_ipv6_setup=0
> /sbin/ip link set dev tun0 up mtu 1500
> /sbin/ip addr add dev tun0 ipaddress/** broadcast ipaddress
> /etc/openvpn/vpnfailsafe.sh tun0 1500 1553 ipaddress ipaddress init
> Too few arguments.
> Too few arguments.

I don't know what's producing these messages, but it's something invoked by vpnfailsafe, so it would be best to look into it.

If you add `set -x` in the second line of vpnfailsafe.sh, every command called by the script will be printed and we can find out.

> RTNETLINK answers: File exists
> ERROR: Linux route add command failed: external program exited with error status: 2
> RTNETLINK answers: File exists
> ERROR: Linux route add command failed: external program exited with error status: 2
> RTNETLINK answers: File exists
> ERROR: Linux route add command failed: external program exited with error status: 2
> Initialization Sequence Completed

This is [fine](https://github.com/wknapik/vpnfailsafe#im-getting-an-error-every-time-i-connect).

If you can run with `set -x` and post the part of the log after ` /etc/openvpn/vpnfailsafe.sh tun0 1500 1553 ipaddress ipaddress init`, we can sort out the last potential issue.

**Comment by newuserhere** [comment] 2017-12-15 17:57
Do you mean, nano vpnfailsafe.sh then change set -eEo pipefail to set -xeEo pipefail
?

**Comment by newuserhere** [comment] 2017-12-15 18:22
+ read -ra numbered_vars
+ readonly numbered_vars foreign_option_1 foreign_option_2 proto_1 proto_2 remote_1 remote_2 remote_port_1 remote_port_2 remote_port_1 remote_port_2
+ readonly dev
+ readonly ifconfig_local
+ readonly ifconfig_netmask
+ readonly ifconfig_remote
+ readonly route_net_gateway
+ readonly route_vpn_gateway
+ readonly script_type
+ readonly trusted_ip
+ readonly trusted_port
+ readonly untrusted_ip
+ readonly untrusted_port
++ basename /etc/openvpn/vpnfailsafe.sh
+ readonly prog=vpnfailsafe.sh
+ prog=vpnfailsafe.sh
+ readonly private_nets=ipaddress/*,ipaddress/*,ipaddress/**,ipaddress/**
+ private_nets=ipaddress/*,ipaddress/*,ipaddress/**,ipaddress/**
+ declare -a remotes cnf_remote_domains cnf_remote_ips
+ read -ra remotes
++ cut -d= -f2
++ sort -n
++ tr '\n' '\t'
++ env
++ grep -oP 'remote_[0-9]+=.*'
+ read -ra cnf_remote_domains
++ sort -u
++ printf '%s\n' domain domain
++ tr '\n' '\t'
+ read -ra cnf_remote_ips
++ printf '%s\n' '' ''
++ sort -u
++ tr '\n' '\t'
+ readonly remotes cnf_remote_domains cnf_remote_ips
+ readonly cur_remote_ip=ipaddress
+ cur_remote_ip=ipaddress
+ readonly cur_port=port
+ cur_port=port
+ trap cleanup INT TERM
+ trap 'err_msg "$LINENO" "$?"' ERR
+ main
+ case "${script_type:-down}" in
+ for f in hosts routes resolv firewall
+ update_hosts up
++ getent -s dns hosts domain
++ grep -v :
+ remote_entries=
+ for f in hosts routes resolv firewall
+ update_routes up
+ local -a resolved_ips
+ read -ra resolved_ips
++ getent -s files hosts domain
++ cut '-d ' -f1
++ tr '\n' '\t'
+ remote_ips=("$cur_remote_ip" "${resolved_ips[@]}" "${cnf_remote_ips[@]}")
+ local -ar remote_ips
+ [[ up == up ]]
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z ipaddress via ipaddress dev enp4s0  ]]
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for remote_ip in "${remote_ips[@]}"
+ [[ -n ipaddress ]]
++ ip route show ipaddress
+ [[ -z '' ]]
+ ip route add ipaddress via ipaddress
+ for net in ipaddress/* ipaddress/*
++ ip route show ipaddress/*
+ [[ -z '' ]]
+ ip route add ipaddress/* via ipaddress
+ for net in ipaddress/* ipaddress/*
++ ip route show ipaddress/*
+ [[ -z '' ]]
+ ip route add ipaddress/* via ipaddress
+ for f in hosts routes resolv firewall
+ update_resolv up
+ case "$@" in
+ local domains= ns=
+ for opt in ${!foreign_option_*}
+ case "${!opt}" in
+ ns+=' ipaddress'
+ for opt in ${!foreign_option_*}
+ case "${!opt}" in
+ ns+=' ipaddress'
+ [[ -n  ipaddress ipaddress ]]
+ echo -e '\n
nameserver ipaddress
nameserver ipaddress'
+ resolvconf -xa tun0
Too few arguments.
Too few arguments.
+ for f in hosts routes resolv firewall
+ update_firewall up
+ for chain in INPUT OUTPUT FORWARD
+ insert_chain INPUT
+ iptables -C INPUT -j VPNFAILSAFE_INPUT
+ iptables -D INPUT -j VPNFAILSAFE_INPUT
+ for opt in F X
+ iptables -F VPNFAILSAFE_INPUT
+ for opt in F X
+ iptables -X VPNFAILSAFE_INPUT
+ iptables -N VPNFAILSAFE_INPUT
+ iptables -I INPUT -j VPNFAILSAFE_INPUT
+ [[ INPUT != FORWARD ]]
+ accept_remotes INPUT
+ case "$@" in
+ local -r icmp_type=reply io=i sd=s states=
++ ip route show ipaddress
++ cut '-d ' -f5
+ local -r public_nic=enp4s0
+ suf=(-m conntrack --ctstate "$states"RELATED,ESTABLISHED -"$io" "${public_nic:?}" -j ACCEPT)
+ local -ar suf
+ (( i=1 ))
+ (( i <= 2 ))
+ local port=remote_port_1
+ local proto=proto_1
+ iptables -A VPNFAILSAFE_INPUT -p udp -s domain --sport port -m conntrack --ctstate RELATED,ESTABLISHED -i enp4s0 -j ACCEPT
+ icmp_rule -C VPNFAILSAFE_INPUT domain
+ icmp_rule -A VPNFAILSAFE_INPUT domain
+ iptables -A VPNFAILSAFE_INPUT -p icmp --icmp-type echo-reply -s domain -m conntrack --ctstate RELATED,ESTABLISHED -i enp4s0 -j RETURN
+ (( ++i ))
+ (( i <= 2 ))
+ local port=remote_port_2
+ local proto=proto_2
+ iptables -A VPNFAILSAFE_INPUT -p udp -s domain --sport port -m conntrack --ctstate RELATED,ESTABLISHED -i enp4s0 -j ACCEPT
+ icmp_rule -C VPNFAILSAFE_INPUT domain
+ (( ++i ))
+ (( i <= 2 ))
+ iptables -S
+ grep -q '^-A VPNFAILSAFE_INPUT .*-s ipaddress/** .*-j ACCEPT$'
+ pass_private_nets INPUT
+ case "$@" in
+ local -r io=i sd=s
+ local -r vpn=ipaddress/ipaddress
+ iptables -A VPNFAILSAFE_INPUT -s ipaddress/ipaddress -i tun0 -j RETURN
+ iptables -A VPNFAILSAFE_INPUT -s ipaddress/*,ipaddress/*,ipaddress/**,ipaddress/** '!' -i tun0 -j RETURN
+ iptables -A VPNFAILSAFE_INPUT -s ipaddress/*,ipaddress/*,ipaddress/**,ipaddress/** -i tun0 -j DROP
+ for iface in "$dev" lo+
+ iptables -A VPNFAILSAFE_INPUT -i tun0 -j RETURN
+ for iface in "$dev" lo+
+ iptables -A VPNFAILSAFE_INPUT -i lo+ -j RETURN
+ drop_other INPUT
+ iptables -A VPNFAILSAFE_INPUT -j DROP
+ for chain in INPUT OUTPUT FORWARD
+ insert_chain OUTPUT
+ iptables -C OUTPUT -j VPNFAILSAFE_OUTPUT
+ iptables -D OUTPUT -j VPNFAILSAFE_OUTPUT
+ for opt in F X
+ iptables -F VPNFAILSAFE_OUTPUT
+ for opt in F X
+ iptables -X VPNFAILSAFE_OUTPUT
+ iptables -N VPNFAILSAFE_OUTPUT
+ iptables -I OUTPUT -j VPNFAILSAFE_OUTPUT
+ [[ OUTPUT != FORWARD ]]
+ accept_remotes OUTPUT
+ case "$@" in
+ local -r icmp_type=request io=o sd=d states=NEW,
++ ip route show ipaddress
++ cut '-d ' -f5
+ local -r public_nic=enp4s0
+ suf=(-m conntrack --ctstate "$states"RELATED,ESTABLISHED -"$io" "${public_nic:?}" -j ACCEPT)
+ local -ar suf
+ (( i=1 ))
+ (( i <= 2 ))
+ local port=remote_port_1
+ local proto=proto_1
+ iptables -A VPNFAILSAFE_OUTPUT -p udp -d domain --dport port -m conntrack --ctstate NEW,RELATED,ESTABLISHED -o enp4s0 -j ACCEPT
+ icmp_rule -C VPNFAILSAFE_OUTPUT domain
+ icmp_rule -A VPNFAILSAFE_OUTPUT domain
+ iptables -A VPNFAILSAFE_OUTPUT -p icmp --icmp-type echo-request -d domain -m conntrack --ctstate NEW,RELATED,ESTABLISHED -o enp4s0 -j RETURN
+ (( ++i ))
+ (( i <= 2 ))
+ local port=remote_port_2
+ local proto=proto_2
+ iptables -A VPNFAILSAFE_OUTPUT -p udp -d domain --dport port -m conntrack --ctstate NEW,RELATED,ESTABLISHED -o enp4s0 -j ACCEPT
+ icmp_rule -C VPNFAILSAFE_OUTPUT domain
+ (( ++i ))
+ (( i <= 2 ))
+ iptables -S
+ grep -q '^-A VPNFAILSAFE_OUTPUT .*-d ipaddress/** .*-j ACCEPT$'
+ pass_private_nets OUTPUT
+ case "$@" in
+ local -r io=o sd=d
+ local -r vpn=ipaddress/ipaddress
+ iptables -A VPNFAILSAFE_OUTPUT -d ipaddress/ipaddress -o tun0 -j RETURN
+ iptables -A VPNFAILSAFE_OUTPUT -d ipaddress/*,ipaddress/*,ipaddress/**,ipaddress/** '!' -o tun0 -j RETURN
+ for iface in "$dev" lo+
+ iptables -A VPNFAILSAFE_OUTPUT -o tun0 -j RETURN
+ for iface in "$dev" lo+
+ iptables -A VPNFAILSAFE_OUTPUT -o lo+ -j RETURN
+ drop_other OUTPUT
+ iptables -A VPNFAILSAFE_OUTPUT -j DROP
+ for chain in INPUT OUTPUT FORWARD
+ insert_chain FORWARD
+ iptables -C FORWARD -j VPNFAILSAFE_FORWARD
+ iptables -D FORWARD -j VPNFAILSAFE_FORWARD
+ for opt in F X
+ iptables -F VPNFAILSAFE_FORWARD
+ for opt in F X
+ iptables -X VPNFAILSAFE_FORWARD
+ iptables -N VPNFAILSAFE_FORWARD
+ iptables -I FORWARD -j VPNFAILSAFE_FORWARD
+ [[ FORWARD != FORWARD ]]
+ pass_private_nets FORWARD
+ case "$@" in
+ local -r io=o sd=d
+ iptables -A VPNFAILSAFE_FORWARD -d ipaddress/*,ipaddress/*,ipaddress/**,ipaddress/** '!' -o tun0 -j RETURN
+ for iface in "$dev" lo+
+ iptables -A VPNFAILSAFE_FORWARD -o tun0 -j RETURN
+ for iface in "$dev" lo+
+ iptables -A VPNFAILSAFE_FORWARD -o lo+ -j RETURN
+ drop_other FORWARD
+ iptables -A VPNFAILSAFE_FORWARD -j DROP
RTNETLINK answers: File exists
ERROR: Linux route add command failed: external program exited with error status: 2
RTNETLINK answers: File exists
ERROR: Linux route add command failed: external program exited with error status: 2
RTNETLINK answers: File exists
ERROR: Linux route add command failed: external program exited with error status: 2
Initialization Sequence Completed

**Comment by wknapik** [comment] 2017-12-18 01:39
Thanks for the log.

> ```
> + echo -e '\n
> nameserver ipaddress
> nameserver ipaddress'
> + resolvconf -xa tun0
> Too few arguments.
> Too few arguments.
> ```

It seems resolvconf is producing the messages.

Are you sure you're using the openresolv package ? As mentioned [here](https://github.com/wknapik/vpnfailsafe#user-content-what-are-the-requirementsassumptionslimitations-), there are multiple implementations of resolvconf and they're not compatible. For me this works with openresolv 3.9.0.

The output of `resolvconf --version` would answer my question.

In any case, the messages look like errors, but apparently resolvconf exits with 0, as if everything worked. You can check `resolvconf -l` and `cat /etc/resolv.conf` to see if the resolvconf invocation was successful.

**Comment by newuserhere** [comment] 2017-12-19 14:54
apt-get install openresolv
openresolv is already the newest version (3.8.0-1).

When I installed openresolv it removed resolvconf.

resolvconf --version
Illegal option --
Illegal option -e
Illegal option -s
Illegal option -o
Illegal option -n
tun0 NetworkManager

resolvconf -l
#resolv.conf from tun0
nameserver vpndns
nameserver vpndns

#resolv.conf from NetworkManager
#Generated by NetworkManager
nameserver vpndns
nameserver vpndns
nameserver myispdns
#NOTE: the libc resolver may not support more than 3 nameservers.
#The nameservers listed below may not be recognized.
nameserver myispdns

cat /etc/resolv.conf
#Generated by resolvconf
nameserver vpndns
nameserver vpndns

**Comment by wknapik** [comment] 2017-12-22 23:35
> apt-get install openresolv
> openresolv is already the newest version (3.8.0-1).
>
> When I installed openresolv it removed resolvconf.

Yes, these two packages are mutually exclusive, but that's ok - we wanted the openresolv implementation.

> resolvconf --version
> Illegal option --
> Illegal option -e
> Illegal option -s
> Illegal option -o
> Illegal option -n
> tun0 NetworkManager

Huh ? What happened there ? The option was parsed as a combination of short options. That's all wrong.
```
% resolvconf --version
openresolv 3.9.0
Copyright (c) 2007-2016 Roy Marples
%
```

> resolvconf -l
> #resolv.conf from tun0
> nameserver vpndns
> nameserver vpndns

The nameservers for the VPN seem to have been set correctly, despite the error messages.

> #resolv.conf from NetworkManager
> #Generated by NetworkManager
> nameserver vpndns
> nameserver vpndns
> nameserver myispdns
> #NOTE: the libc resolver may not support more than 3 nameservers.
> #The nameservers listed below may not be recognized.
> nameserver myispdns

Something's wrong here. Why are your ISP's DNS servers mixed with your VPN's DNS servers ? Perhaps you manually edited the list at some point ? This should only contain your ISP's servers.

> cat /etc/resolv.conf
> #Generated by resolvconf
> nameserver vpndns
> nameserver vpndns

This seems fine. And that's the part that matters most.

So something's up with your resolvconf/openresolv, not sure what, but otherwise things look fine, based on what you pasted.

If you want to get to the bottom of it, you could open resolvconf in your editor to make sure it's the version by Roy Marples (which the openresolv package should contain).

**Comment by wknapik** [comment] 2017-12-23 00:25
I just tested this on debian stretch. Apparently, support for the `--version` switch was added after 3.8.0, so this is expected behavior, but when I used openvpn+vpnfailsafe, I didn't see the "Too few arguments." message.

**Comment by wknapik** [comment] 2017-12-29 15:59
So, to sum up - it seems that everything is working, but there are some mysterious messages from resolvconf (not reproducible for me on Debian), that don't seem to affect its operation.

Please let me know if you need any further help, otherwise I'll close this issue.

**Comment by wknapik** [comment] 2018-01-07 17:22
Ok, given it's been 19 days since last communication, I assume there's no point in keeping this issue open. Feel free to reopen, or open a new one if needed.

**Closed as completed by wknapik** 2018-01-07 17:22 UTC

**Comment by roboyoshi** [comment] 2018-12-18 09:58
If anyone else stumbles upon this issue: The openresolv packages in debian stable are v3.8.0 and even unstable gives v3.8.0 as of 12/2018 (At least on my proxmox cluster that is..).

If you want to get rid of the "Too many arguments" Issue, you can simply compile the 3.9.0 yourself:

```sh
apt-get purge openresolv
cd /tmp && wget https://roy.marples.name/downloads/openresolv/openresolv-3.9.0.tar.xz
tar xvf openresolv-3.9.0.tar.xz
cd openresolv-* && ./configure && make && make install
cd /tmp && rm -rf openresolv-*
resolvconf --version
```

**Comment by gregt590** [comment] 2020-09-08 06:11
I ran into this problem installing and running openvpn 2.4.7 on Raspberry Pi Operating System.  Updating resolvconf from 3.8.0-1 to 3.9.0 as shown immediately above eliminated the two "Too few arguments." error messages following "dhcp-option DNS" and invocation of /etc/openvpn/update-resolv-conf statement in my openvpn's log for my system.  Thanks!
