### ISSUE TITLE
Server not pingable

### ISSUE THREAD

**Issue by mfuellbier** [wknapik/vpnfailsafe#9] opened 2016-12-11 23:16 UTC
#### Setup
Own openvpn server and one openvpn client. 

#### Issue
Using openvpn **without** vpnfailsafe, the vpn server **is** pingable. Everything is OK.
Using openvpn **with** vpnfailsafe, the vpn server **is not** pingable. Neither over VPN IP, nor by public IP or domain.

Do you have an idea, why?

#### Further information

These are my configs
[client.conf.txt](https://github.com/wknapik/vpnfailsafe/files/644844/client.conf.txt)
[server.conf.txt](https://github.com/wknapik/vpnfailsafe/files/644846/server.conf.txt)
[ipp.txt](https://github.com/wknapik/vpnfailsafe/files/644848/ipp.txt)

example.com: servers public domain
x.x.x.x: servers public IP
10.9.8.1: servers internal vpn ip (tun-device)

After establishing the vpn connection **with** vpnfailsafe, i get the following outputs on the **client**.
```bash
$ ping x.x.x.x
PING x.x.x.x (x.x.x.x) 56(84) bytes of data.
ping: sendmsg: Operation not permitted
ping: sendmsg: Operation not permitted
^C
--- x.x.x.x ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1013ms
```
```bash
$ ping example.com
PING example.com (x.x.x.x) 56(84) bytes of data.
ping: sendmsg: Operation not permitted
ping: sendmsg: Operation not permitted
^C
--- example.com ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1024ms
```
```bash
$ ping 10.9.8.1
PING 10.9.8.1 (10.9.8.1) 56(84) bytes of data.
^C
--- 10.9.8.1 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3027ms
```
```bash
$ ip a
[...]
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
   link/none 
    inet 10.9.8.6 peer 10.9.8.5/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::db4a:cc4:d4dc:ebe7/64 scope link flags 800 
       valid_lft forever preferred_lft forever
```
```bash
$ ip route
0.0.0.0/1 via 10.9.8.5 dev tun0 
default via 192.168.0.1 dev eth0 proto static metric 600 
10.9.8.0/24 via 10.9.8.5 dev tun0 
10.9.8.5 dev tun0 proto kernel scope link src 10.9.8.6
128.0.0.0/1 via 10.9.8.5 dev tun0
x.x.x.x via 192.168.0.1 dev eth0 
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.28 metric 600 
```
```bash
$ iptables -nvL
Chain INPUT (policy ACCEPT 8897 packets, 1667K bytes)
 pkts bytes target     prot opt in     out     source               destination         
10874 2699K VPNFAILSAFE_INPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 VPNFAILSAFE_FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 9085 packets, 1010K bytes)
 pkts bytes target     prot opt in     out     source               destination         
11886 1830K VPNFAILSAFE_OUTPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0  

Chain VPNFAILSAFE_FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      !tun0   0.0.0.0/0            127.0.0.0/8         
    0     0 RETURN     all  --  *      !tun0   0.0.0.0/0            10.0.0.0/8          
    0     0 RETURN     all  --  *      !tun0   0.0.0.0/0            172.16.0.0/12       
    0     0 RETURN     all  --  *      !tun0   0.0.0.0/0            192.168.0.0/16      
    0     0 RETURN     all  --  *      tun0    0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain VPNFAILSAFE_INPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   70 18238 ACCEPT     udp  --  eth0   *       x.x.x.x              0.0.0.0/0            udp spt:1194 ctstate RELATED,ESTABLISHED
    0     0 RETURN     all  --  tun0   *       10.9.8.5             0.0.0.0/0           
    0     0 RETURN     all  --  !tun0  *       127.0.0.0/8          0.0.0.0/0           
    0     0 RETURN     all  --  !tun0  *       10.0.0.0/8           0.0.0.0/0           
    0     0 RETURN     all  --  !tun0  *       172.16.0.0/12        0.0.0.0/0           
  883 97794 RETURN     all  --  !tun0  *       192.168.0.0/16       0.0.0.0/0           
    0     0 DROP       all  --  tun0   *       127.0.0.0/8          0.0.0.0/0           
    3   252 DROP       all  --  tun0   *       10.0.0.0/8           0.0.0.0/0           
    0     0 DROP       all  --  tun0   *       172.16.0.0/12        0.0.0.0/0           
    0     0 DROP       all  --  tun0   *       192.168.0.0/16       0.0.0.0/0           
   48 10464 RETURN     all  --  tun0   *       0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain VPNFAILSAFE_OUTPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  110 26563 ACCEPT     udp  --  *      eth0    0.0.0.0/0            x.x.x.x       udp dpt:1194 ctstate NEW,RELATED,ESTABLISHED
    0     0 RETURN     all  --  *      tun0    0.0.0.0/0            10.9.8.5            
    0     0 RETURN     all  --  *      !tun0   0.0.0.0/0            127.0.0.0/8         
    0     0 RETURN     all  --  *      !tun0   0.0.0.0/0            10.0.0.0/8          
    0     0 RETURN     all  --  *      !tun0   0.0.0.0/0            172.16.0.0/12       
  882 64250 RETURN     all  --  *      !tun0   0.0.0.0/0            192.168.0.0/16      
   93 12694 RETURN     all  --  *      tun0    0.0.0.0/0            0.0.0.0/0           
   94  7776 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

**Comment by wknapik** [comment] 2016-12-12 17:37
Just pushed a fix, please let me know if it resolves the problem for you.

PS. `iptables -nvL` output is not terribly useful. `iptables -S` works much better.

**Comment by mfuellbier** [comment] 2016-12-12 22:19
Thanks for the quick fix.
```ping x.x.x.x``` and ```ping example.com``` work fine now.

What still does not work is ```ping 10.9.8.1```.
Besides that, I still neither can connect to the http(s) server running on the openvpn machine, nor can I ```ssh``` to it - no matter if I try to connect via IP or via hostname. Maybe I have to modify the server.conf and push some routes or something. I'll play around a bit.

**Comment by wknapik** [comment] 2016-12-13 11:12
> ping x.x.x.x and ping example.com work fine now.

Great.

> What still does not work is ping 10.9.8.1.

Hmm, that should work. Lines 129 and 133 of the script should pass that to pre-existing iptables rules. Could your pre-vpnfailsafe firewall (on the client) be blocking those pings ? Can it be the firewall/sysctl settings on the server ?

> Besides that, I still neither can connect to the http(s) server running on the openvpn machine, nor can I ssh to it - no matter if I try to connect via IP or via hostname. 

Well, this situation is clear at least. `vpnfailsafe` sets the route to your configured vpn servers over your regular interface (not tun0) and then prevents traffic to the internet over that device, unless it's to the vpn service (host/port/proto).

There are 3 ways out of it:
* Relax the rules set by `vpnfailsafe` and allow all traffic to/from the vpn servers, regardless of protocol/port, affecting all `vpnfailsafe` users
* Add rules explicitly allowing connections to the services running on the vpn server. Those could be saved with the rest of the firewall rules that exist regardless of `vpnfailsafe`
* Access those services using a different IP, than the public IP used in the vpn client config, like the internal vpn-based IP (this may, or may not require adding explicit iptables rules to allow it, depending on how the firewall looked to begin with)

I don't really like option 1. It could be turned off by default and switched on with an argument to `vpnfailsafe`, but that's additional code to account for what seems like an uncommon case... I don't know. I'd rather explore other options first.

Option 2 is simple, but does require explicit action by the user.

Option 3 should Just Work (TM), if your firewall doesn't restrict such traffic.

Could you attach the output of `iptables -S` ? And also try options 2 and/or 3 ? 

The simplest way to test if it's `vpnfailsafe`'s rules blocking the connections, or yours, would be to flush all firewall rules, connect to the vpn with and without `vpnfailsafe` and check if the connections (ping/http(s)/ssh) work using any possible IPs.

**Comment by mfuellbier** [comment] 2016-12-13 16:25
withouth vpnfailsafe:
```
$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```
with vpnfailsafe:
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N VPNFAILSAFE_FORWARD
-N VPNFAILSAFE_INPUT
-N VPNFAILSAFE_OUTPUT
-A INPUT -j VPNFAILSAFE_INPUT
-A FORWARD -j VPNFAILSAFE_FORWARD
-A OUTPUT -j VPNFAILSAFE_OUTPUT
-A VPNFAILSAFE_FORWARD -d 127.0.0.0/8 ! -o tun0 -j RETURN
-A VPNFAILSAFE_FORWARD -d 10.0.0.0/8 ! -o tun0 -j RETURN
-A VPNFAILSAFE_FORWARD -d 172.16.0.0/12 ! -o tun0 -j RETURN
-A VPNFAILSAFE_FORWARD -d 192.168.0.0/16 ! -o tun0 -j RETURN
-A VPNFAILSAFE_FORWARD -o tun0 -j RETURN
-A VPNFAILSAFE_FORWARD -o lo+ -j RETURN
-A VPNFAILSAFE_FORWARD -j DROP
-A VPNFAILSAFE_INPUT -s x.x.x.x/32 -i eth0 -p udp -m udp --sport 1194 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A VPNFAILSAFE_INPUT -s x.x.x.x/32 -i eth0 -p icmp -m icmp --icmp-type 0 -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
-A VPNFAILSAFE_INPUT -s 10.9.8.5/32 -i tun0 -j RETURN
-A VPNFAILSAFE_INPUT -s 127.0.0.0/8 ! -i tun0 -j RETURN
-A VPNFAILSAFE_INPUT -s 10.0.0.0/8 ! -i tun0 -j RETURN
-A VPNFAILSAFE_INPUT -s 172.16.0.0/12 ! -i tun0 -j RETURN
-A VPNFAILSAFE_INPUT -s 192.168.0.0/16 ! -i tun0 -j RETURN
-A VPNFAILSAFE_INPUT -s 127.0.0.0/8 -i tun0 -j DROP
-A VPNFAILSAFE_INPUT -s 10.0.0.0/8 -i tun0 -j DROP
-A VPNFAILSAFE_INPUT -s 172.16.0.0/12 -i tun0 -j DROP
-A VPNFAILSAFE_INPUT -s 192.168.0.0/16 -i tun0 -j DROP
-A VPNFAILSAFE_INPUT -i tun0 -j RETURN
-A VPNFAILSAFE_INPUT -i lo+ -j RETURN
-A VPNFAILSAFE_INPUT -j DROP
-A VPNFAILSAFE_OUTPUT -d x.x.x.x/32 -o eth0 -p udp -m udp --dport 1194 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT
-A VPNFAILSAFE_OUTPUT -d x.x.x.x/32 -o eth0 -p icmp -m icmp --icmp-type 8 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j RETURN
-A VPNFAILSAFE_OUTPUT -d 10.9.8.5/32 -o tun0 -j RETURN
-A VPNFAILSAFE_OUTPUT -d 127.0.0.0/8 ! -o tun0 -j RETURN
-A VPNFAILSAFE_OUTPUT -d 10.0.0.0/8 ! -o tun0 -j RETURN
-A VPNFAILSAFE_OUTPUT -d 172.16.0.0/12 ! -o tun0 -j RETURN
-A VPNFAILSAFE_OUTPUT -d 192.168.0.0/16 ! -o tun0 -j RETURN
-A VPNFAILSAFE_OUTPUT -o tun0 -j RETURN
-A VPNFAILSAFE_OUTPUT -o lo+ -j RETURN
-A VPNFAILSAFE_OUTPUT -j DROP
```
I am not really sure, where the 10.9.8.5 is coming from. It also appears in the ```ip a``` and ```ip route``` output, as seen in the first comment.

As I said, without vpnfailsafe, the connection to the vpn server works using any IPs. But with vpnfailsafe, no connection to the vpn server works at all - only connection to the internet works.

**Comment by wknapik** [comment] 2016-12-13 18:22
10.9.8.5 is what `vpnfailsafe` got from environment variables set by the OpenVPN client as the VPN-level gateway.

And it *works* as one.

Here's a quick guess based just on the config file and the man page, not confirmed by recreating your full setup:

You're using --server without `nopool` and --ifconfig-pool-persist (which probably also implies --ifconfig-pool). From the man page:
```
--ifconfig-pool start-IP end-IP [netmask]
  Set aside a pool of subnets to be dynamically allocated to connecting clients, similar to a DHCP server.  For tun-style tunnels, each client will be given a /30 subnet (for interoperability with Windows clients).
```
So once the connection is established, you're operating in net30 topology, with 10.9.8.5 as your VPN gateway and 10.9.8.6 as your client's address. That's what `vpnfailsafe` sees.

Your services may be available at 10.9.8.5 and you may be able to use it instead of 10.9.8.1. If not, you could just stop using pooling, to have access to 10.9.8.1 from the client, or redirect traffic from 10.9.8.5 to 10.9.8.1 on the server.

If this answer is not good enough, please add `env; set -x` in the second line of the script and post the output. This would provide more information.

**Comment by wknapik** [comment] 2016-12-15 13:14
Hi @maikeloni. Did I manage to explain the situation ? `vpnfailsafe` most likely doesn't know about 10.9.8.1 due to the pooling you're using, so it has no way of adding appropriate rules. If you don't want to change your config, or the firewall on the server, you could just add these two rules to your pre-vpnfailsafe firewall on the client:

either
```
# More permissive - all traffic to and from 10.9.8.1.
iptables -A OUTPUT -d 10.9.8.1 -o tun0 -j ACCEPT
iptables -A INPUT -s 10.9.8.1 -i tun0 -j ACCEPT
```
or
```
# Only traffic initiated by the client. If that's ok, it's the better choice.
iptables -A INPUT -s 10.9.8.1 -i tun0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -d 10.9.8.1 -o tun0 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT
```

and services at 10.9.8.1 would become available to you. Having to add those rules manually is not ideal, but if you want to keep your current setup without changes, they'd get the job done. And it's only a one time effort.

**Comment by mfuellbier** [comment] 2016-12-15 14:08
Hi @wknapik, sorry that I didn't answer earlier, quiet busy these days ...
10.9.8.5 does not work either. But the proposals in your last post work. I also came up with these kind of solutions. As far as I tested it, it works fine for me. I didn't implement this solution yet for temporal reasons. I suppose that this issue is solved though.

Thank you very much for your quick and proficient help!

**Comment by wknapik** [comment] 2016-12-15 14:13
No problem :) Glad to hear things are working for you. And thanks for the report @maikeloni, I totally missed the issue of pingability. 
I'll close this ticket, but feel free to post any further comments/findings if you like.
Cheers.

**Closed as completed by wknapik** 2016-12-15 14:13 UTC
